apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname2
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                                                 # [OPTIONAL] if not provided, will default to "false". Set to "true" if using pod identities.
    useVMManagedIdentity: "false"                                           # [OPTIONAL] if not provided, will default to "false". Set to "true" if using managed identities.
    userAssignedIdentityID: "9c75463e-ed90-4240-b27e-47846d24296d" 
    keyvaultName: "kv-uat001"                                        # [REQUIRED] the name of the key vault
    objects:  |
      array:
        - |
          objectName: SQLSERVER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectType: secret
        - |
          objectName: SQLUSER
          objectType: secret   
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                                                    # [REQUIRED] the tenant ID of the key vault